# Generated by Django 4.1.5 on 2023-01-28 13:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_oauth_access_token'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messagetype',
            old_name='message_type',
            new_name='state',
        ),
        migrations.AlterField(
            model_name='oauth',
            name='access_token',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 28, 13, 35, 29, 243850, tzinfo=datetime.timezone.utc)),
        ),
    ]
