# Generated by Django 4.1.5 on 2023-01-28 19:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_message_type_messagetype_state_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messagelog',
            old_name='message_types',
            new_name='message_type',
        ),
        migrations.AlterField(
            model_name='oauth',
            name='access_token',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 28, 19, 20, 20, 636901, tzinfo=datetime.timezone.utc)),
        ),
    ]
